export const GLOBAL_CITIES = [
  "London",
  "Manchester",
  "Birmingham",
  "Leeds",
  "Glasgow",
  "Sheffield",
  "Bradford",
  "Liverpool",
  "Edinburgh",
  "Bristol",
  "Cardiff",
  "Leicester",
  "Wakefield",
  "Coventry",
  "Nottingham",
  "Newcastle",
  "Brighton",
  "Hull",
  "Plymouth",
  "Stoke-on-Trent",
  "Wolverhampton",
  "Derby",
  "Swansea",
  "Southampton", // UK cities
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Charlotte",
  "San Francisco",
  "Indianapolis",
  "Seattle",
  "Denver",
  "Washington",
  "Boston", // US cities
  "Toronto",
  "Montreal",
  "Vancouver",
  "Calgary",
  "Edmonton",
  "Ottawa",
  "Winnipeg",
  "Quebec City", // Canadian cities
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Adelaide",
  "Gold Coast",
  "Newcastle",
  "Canberra", // Australian cities
  "Kabul",
  "Kandahar",
  "Herat",
  "Mazar-i-Sharif",
  "Jalalabad",
  "Kunduz",
  "Ghazni",
  "Balkh", // Afghan cities
  "Dubai",
  "Abu Dhabi",
  "Sharjah",
  "Al Ain",
  "Ajman",
  "Ras Al Khaimah",
  "Fujairah", // UAE cities
  "Doha",
  "Al Rayyan",
  "Al Wakrah",
  "Al Khor",
  "Umm Salal", // Qatar cities
  "Other",
];
