name: CI

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop, staging]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-type-check:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: aroosi-mobile/package-lock.json
      
      - name: Install dependencies
        working-directory: aroosi-mobile
        run: npm ci
      
      - name: Run ESLint
        working-directory: aroosi-mobile
        run: npm run lint
      
      - name: Type check
        working-directory: aroosi-mobile
        run: npm run type-check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: aroosi-mobile/package-lock.json
      
      - name: Install dependencies
        working-directory: aroosi-mobile
        run: npm ci
      
      - name: Run unit tests
        working-directory: aroosi-mobile
        run: npm run test:unit -- --coverage
      
      - name: Run integration tests
        working-directory: aroosi-mobile
        run: npm run test:integration
      
      - name: Run messaging tests
        working-directory: aroosi-mobile
        run: npm run test:messaging
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: aroosi-mobile/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run security audit
        working-directory: aroosi-mobile
        run: npm audit --audit-level=high
      
      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-extended
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [lint-and-type-check, test, security]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: aroosi-mobile/package-lock.json
      
      - name: Install dependencies
        working-directory: aroosi-mobile
        run: npm ci
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Build for iOS
        working-directory: aroosi-mobile
        run: eas build --platform ios --non-interactive --no-wait
      
      - name: Build for Android
        working-directory: aroosi-mobile
        run: eas build --platform android --non-interactive --no-wait