import type { DialCodeEntry } from "./countryDialCodes";

export const COUNTRY_DIAL_CODES: DialCodeEntry[] = [
  { value: "UK", label: "United Kingdom", dialCode: "+44", flag: "🇬🇧" },
  { value: "Afghanistan", label: "Afghanistan", dialCode: "+93", flag: "🇦🇫" },
  { value: "Albania", label: "Albania", dialCode: "+355", flag: "🇦🇱" },
  { value: "Algeria", label: "Algeria", dialCode: "+213", flag: "🇩🇿" },
  { value: "Andorra", label: "Andorra", dialCode: "+376", flag: "🇦🇩" },
  { value: "Angola", label: "Angola", dialCode: "+244", flag: "🇦🇴" },
  { value: "Argentina", label: "Argentina", dialCode: "+54", flag: "🇦🇷" },
  { value: "Armenia", label: "Armenia", dialCode: "+374", flag: "🇦🇲" },
  { value: "Australia", label: "Australia", dialCode: "+61", flag: "🇦🇺" },
  { value: "Austria", label: "Austria", dialCode: "+43", flag: "🇦🇹" },

  { value: "Azerbaijan", label: "Azerbaijan", dialCode: "+994", flag: "🇦🇿" },
  { value: "Bahamas", label: "Bahamas", dialCode: "+1242", flag: "🇧🇸" },
  { value: "Bahrain", label: "Bahrain", dialCode: "+973", flag: "🇧🇭" },
  { value: "Bangladesh", label: "Bangladesh", dialCode: "+880", flag: "🇧🇩" },
  { value: "Barbados", label: "Barbados", dialCode: "+1246", flag: "🇧🇧" },
  { value: "Belarus", label: "Belarus", dialCode: "+375", flag: "🇧🇾" },
  { value: "Belgium", label: "Belgium", dialCode: "+32", flag: "🇧🇪" },
  { value: "Belize", label: "Belize", dialCode: "+501", flag: "🇧🇿" },
  { value: "Benin", label: "Benin", dialCode: "+229", flag: "🇧🇯" },
  { value: "Bhutan", label: "Bhutan", dialCode: "+975", flag: "🇧🇹" },

  { value: "Bolivia", label: "Bolivia", dialCode: "+591", flag: "🇧🇴" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", dialCode: "+387", flag: "🇧🇦" },
  { value: "Botswana", label: "Botswana", dialCode: "+267", flag: "🇧🇼" },
  { value: "Brazil", label: "Brazil", dialCode: "+55", flag: "🇧🇷" },
  { value: "Brunei", label: "Brunei", dialCode: "+673", flag: "🇧🇳" },
  { value: "Bulgaria", label: "Bulgaria", dialCode: "+359", flag: "🇧🇬" },
  { value: "Burkina Faso", label: "Burkina Faso", dialCode: "+226", flag: "🇧🇫" },
  { value: "Burundi", label: "Burundi", dialCode: "+257", flag: "🇧🇮" },
  { value: "Cambodia", label: "Cambodia", dialCode: "+855", flag: "🇰🇭" },
  { value: "Cameroon", label: "Cameroon", dialCode: "+237", flag: "🇨🇲" },

  { value: "Canada", label: "Canada", dialCode: "+1", flag: "🇨🇦" },
  { value: "Cape Verde", label: "Cape Verde", dialCode: "+238", flag: "🇨🇻" },
  { value: "Central African Republic", label: "Central African Republic", dialCode: "+236", flag: "🇨🇫" },
  { value: "Chad", label: "Chad", dialCode: "+235", flag: "🇹🇩" },
  { value: "Chile", label: "Chile", dialCode: "+56", flag: "🇨🇱" },
  { value: "China", label: "China", dialCode: "+86", flag: "🇨🇳" },
  { value: "Colombia", label: "Colombia", dialCode: "+57", flag: "🇨🇴" },
  { value: "Comoros", label: "Comoros", dialCode: "+269", flag: "🇰🇲" },
  { value: "Congo (Republic)", label: "Congo (Republic)", dialCode: "+242", flag: "🇨🇬" },
  { value: "Congo (DRC)", label: "Congo (DRC)", dialCode: "+243", flag: "🇨🇩" },
  { value: "Costa Rica", label: "Costa Rica", dialCode: "+506", flag: "🇨🇷" },
  { value: "Cote d’Ivoire", label: "Cote d’Ivoire", dialCode: "+225", flag: "🇨🇮" },
  { value: "Croatia", label: "Croatia", dialCode: "+385", flag: "🇭🇷" },
  { value: "Cuba", label: "Cuba", dialCode: "+53", flag: "🇨🇺" },
  { value: "Cyprus", label: "Cyprus", dialCode: "+357", flag: "🇨🇾" },
  { value: "Czech Republic", label: "Czech Republic", dialCode: "+420", flag: "🇨🇿" },
  { value: "Denmark", label: "Denmark", dialCode: "+45", flag: "🇩🇰" },
  { value: "Djibouti", label: "Djibouti", dialCode: "+253", flag: "🇩🇯" },
  { value: "Dominica", label: "Dominica", dialCode: "+1767", flag: "🇩🇲" },
  { value: "Dominican Republic", label: "Dominican Republic", dialCode: "+1809", flag: "🇩🇴" },

  { value: "Ecuador", label: "Ecuador", dialCode: "+593", flag: "🇪🇨" },
  { value: "Egypt", label: "Egypt", dialCode: "+20", flag: "🇪🇬" },
  { value: "El Salvador", label: "El Salvador", dialCode: "+503", flag: "🇸🇻" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", dialCode: "+240", flag: "🇬🇶" },
  { value: "Eritrea", label: "Eritrea", dialCode: "+291", flag: "🇪🇷" },
  { value: "Estonia", label: "Estonia", dialCode: "+372", flag: "🇪🇪" },
  { value: "Eswatini", label: "Eswatini", dialCode: "+268", flag: "🇸🇿" },
  { value: "Ethiopia", label: "Ethiopia", dialCode: "+251", flag: "🇪🇹" },
  { value: "Fiji", label: "Fiji", dialCode: "+679", flag: "🇫🇯" },
  { value: "Finland", label: "Finland", dialCode: "+358", flag: "🇫🇮" },

  { value: "France", label: "France", dialCode: "+33", flag: "🇫🇷" },
  { value: "Gabon", label: "Gabon", dialCode: "+241", flag: "🇬🇦" },
  { value: "Gambia", label: "Gambia", dialCode: "+220", flag: "🇬🇲" },
  { value: "Georgia", label: "Georgia", dialCode: "+995", flag: "🇬🇪" },
  { value: "Germany", label: "Germany", dialCode: "+49", flag: "🇩🇪" },
  { value: "Ghana", label: "Ghana", dialCode: "+233", flag: "🇬🇭" },
  { value: "Greece", label: "Greece", dialCode: "+30", flag: "🇬🇷" },
  { value: "Grenada", label: "Grenada", dialCode: "+1473", flag: "🇬🇩" },
  { value: "Guatemala", label: "Guatemala", dialCode: "+502", flag: "🇬🇹" },
  { value: "Guinea", label: "Guinea", dialCode: "+224", flag: "🇬🇳" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau", dialCode: "+245", flag: "🇬🇼" },
  { value: "Guyana", label: "Guyana", dialCode: "+592", flag: "🇬🇾" },
  { value: "Haiti", label: "Haiti", dialCode: "+509", flag: "🇭🇹" },
  { value: "Honduras", label: "Honduras", dialCode: "+504", flag: "🇭🇳" },
  { value: "Hong Kong", label: "Hong Kong", dialCode: "+852", flag: "🇭🇰" },
  { value: "Hungary", label: "Hungary", dialCode: "+36", flag: "🇭🇺" },
  { value: "Iceland", label: "Iceland", dialCode: "+354", flag: "🇮🇸" },
  { value: "India", label: "India", dialCode: "+91", flag: "🇮🇳" },
  { value: "Indonesia", label: "Indonesia", dialCode: "+62", flag: "🇮🇩" },
  { value: "Iran", label: "Iran", dialCode: "+98", flag: "🇮🇷" },

  { value: "Iraq", label: "Iraq", dialCode: "+964", flag: "🇮🇶" },
  { value: "Ireland", label: "Ireland", dialCode: "+353", flag: "🇮🇪" },
  { value: "Israel", label: "Israel", dialCode: "+972", flag: "🇮🇱" },
  { value: "Italy", label: "Italy", dialCode: "+39", flag: "🇮🇹" },
  { value: "Jamaica", label: "Jamaica", dialCode: "+1876", flag: "🇯🇲" },
  { value: "Japan", label: "Japan", dialCode: "+81", flag: "🇯🇵" },
  { value: "Jordan", label: "Jordan", dialCode: "+962", flag: "🇯🇴" },
  { value: "Kazakhstan", label: "Kazakhstan", dialCode: "+7", flag: "🇰🇿" },
  { value: "Kenya", label: "Kenya", dialCode: "+254", flag: "🇰🇪" },
  { value: "Kiribati", label: "Kiribati", dialCode: "+686", flag: "🇰🇮" },
  { value: "Kuwait", label: "Kuwait", dialCode: "+965", flag: "🇰🇼" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", dialCode: "+996", flag: "🇰🇬" },
  { value: "Laos", label: "Laos", dialCode: "+856", flag: "🇱🇦" },
  { value: "Latvia", label: "Latvia", dialCode: "+371", flag: "🇱🇻" },
  { value: "Lebanon", label: "Lebanon", dialCode: "+961", flag: "🇱🇧" },
  { value: "Lesotho", label: "Lesotho", dialCode: "+266", flag: "🇱🇸" },
  { value: "Liberia", label: "Liberia", dialCode: "+231", flag: "🇱🇷" },
  { value: "Libya", label: "Libya", dialCode: "+218", flag: "🇱🇾" },
  { value: "Liechtenstein", label: "Liechtenstein", dialCode: "+423", flag: "🇱🇮" },
  { value: "Lithuania", label: "Lithuania", dialCode: "+370", flag: "🇱🇹" },

  { value: "Luxembourg", label: "Luxembourg", dialCode: "+352", flag: "🇱🇺" },
  { value: "Madagascar", label: "Madagascar", dialCode: "+261", flag: "🇲🇬" },
  { value: "Malawi", label: "Malawi", dialCode: "+265", flag: "🇲🇼" },
  { value: "Malaysia", label: "Malaysia", dialCode: "+60", flag: "🇲🇾" },
  { value: "Maldives", label: "Maldives", dialCode: "+960", flag: "🇲🇻" },
  { value: "Mali", label: "Mali", dialCode: "+223", flag: "🇲🇱" },
  { value: "Malta", label: "Malta", dialCode: "+356", flag: "🇲🇹" },
  { value: "Marshall Islands", label: "Marshall Islands", dialCode: "+692", flag: "🇲🇭" },
  { value: "Mauritania", label: "Mauritania", dialCode: "+222", flag: "🇲🇷" },
  { value: "Mauritius", label: "Mauritius", dialCode: "+230", flag: "🇲🇺" },

  { value: "Mexico", label: "Mexico", dialCode: "+52", flag: "🇲🇽" },
  { value: "Micronesia", label: "Micronesia", dialCode: "+691", flag: "🇫🇲" },
  { value: "Moldova", label: "Moldova", dialCode: "+373", flag: "🇲🇩" },
  { value: "Monaco", label: "Monaco", dialCode: "+377", flag: "🇲🇨" },
  { value: "Mongolia", label: "Mongolia", dialCode: "+976", flag: "🇲🇳" },
  { value: "Montenegro", label: "Montenegro", dialCode: "+382", flag: "🇲🇪" },
  { value: "Morocco", label: "Morocco", dialCode: "+212", flag: "🇲🇦" },
  { value: "Mozambique", label: "Mozambique", dialCode: "+258", flag: "🇲🇿" },
  { value: "Myanmar", label: "Myanmar", dialCode: "+95", flag: "🇲🇲" },
  { value: "Namibia", label: "Namibia", dialCode: "+264", flag: "🇳🇦" },
  { value: "Nauru", label: "Nauru", dialCode: "+674", flag: "🇳🇷" },
  { value: "Nepal", label: "Nepal", dialCode: "+977", flag: "🇳🇵" },
  { value: "Netherlands", label: "Netherlands", dialCode: "+31", flag: "🇳🇱" },
  { value: "New Zealand", label: "New Zealand", dialCode: "+64", flag: "🇳🇿" },
  { value: "Nicaragua", label: "Nicaragua", dialCode: "+505", flag: "🇳🇮" },
  { value: "Niger", label: "Niger", dialCode: "+227", flag: "🇳🇪" },
  { value: "Nigeria", label: "Nigeria", dialCode: "+234", flag: "🇳🇬" },
  { value: "North Korea", label: "North Korea", dialCode: "+850", flag: "🇰🇵" },
  { value: "North Macedonia", label: "North Macedonia", dialCode: "+389", flag: "🇲🇰" },
  { value: "Norway", label: "Norway", dialCode: "+47", flag: "🇳🇴" },

  { value: "Oman", label: "Oman", dialCode: "+968", flag: "🇴🇲" },
  { value: "Pakistan", label: "Pakistan", dialCode: "+92", flag: "🇵🇰" },
  { value: "Palau", label: "Palau", dialCode: "+680", flag: "🇵🇼" },
  { value: "Panama", label: "Panama", dialCode: "+507", flag: "🇵🇦" },
  { value: "Papua New Guinea", label: "Papua New Guinea", dialCode: "+675", flag: "🇵🇬" },
  { value: "Paraguay", label: "Paraguay", dialCode: "+595", flag: "🇵🇾" },
  { value: "Peru", label: "Peru", dialCode: "+51", flag: "🇵🇪" },
  { value: "Philippines", label: "Philippines", dialCode: "+63", flag: "🇵🇭" },
  { value: "Poland", label: "Poland", dialCode: "+48", flag: "🇵🇱" },
  { value: "Portugal", label: "Portugal", dialCode: "+351", flag: "🇵🇹" },
  { value: "Qatar", label: "Qatar", dialCode: "+974", flag: "🇶🇦" },
  { value: "Romania", label: "Romania", dialCode: "+40", flag: "🇷🇴" },
  { value: "Russia", label: "Russia", dialCode: "+7", flag: "🇷🇺" },
  { value: "Rwanda", label: "Rwanda", dialCode: "+250", flag: "🇷🇼" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis", dialCode: "+1869", flag: "🇰🇳" },
  { value: "Saint Lucia", label: "Saint Lucia", dialCode: "+1754", flag: "🇱🇨" },
  { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines", dialCode: "+1784", flag: "🇻🇨" },
  { value: "Samoa", label: "Samoa", dialCode: "+685", flag: "🇼🇸" },
  { value: "San Marino", label: "San Marino", dialCode: "+378", flag: "🇸🇲" },
  { value: "Sao Tome and Principe", label: "Sao Tome and Principe", dialCode: "+239", flag: "🇸🇹" },

  { value: "Saudi Arabia", label: "Saudi Arabia", dialCode: "+966", flag: "🇸🇦" },
  { value: "Senegal", label: "Senegal", dialCode: "+221", flag: "🇸🇳" },
  { value: "Serbia", label: "Serbia", dialCode: "+381", flag: "🇷🇸" },
  { value: "Seychelles", label: "Seychelles", dialCode: "+248", flag: "🇸🇨" },
  { value: "Sierra Leone", label: "Sierra Leone", dialCode: "+232", flag: "🇸🇱" },
  { value: "Singapore", label: "Singapore", dialCode: "+65", flag: "🇸🇬" },
  { value: "Slovakia", label: "Slovakia", dialCode: "+421", flag: "🇸🇰" },
  { value: "Slovenia", label: "Slovenia", dialCode: "+386", flag: "🇸🇮" },
  { value: "Solomon Islands", label: "Solomon Islands", dialCode: "+677", flag: "🇸🇧" },
  { value: "Somalia", label: "Somalia", dialCode: "+252", flag: "🇸🇴" },
  { value: "South Africa", label: "South Africa", dialCode: "+27", flag: "🇿🇦" },
  { value: "South Korea", label: "South Korea", dialCode: "+82", flag: "🇰🇷" },
  { value: "South Sudan", label: "South Sudan", dialCode: "+211", flag: "🇸🇸" },
  { value: "Spain", label: "Spain", dialCode: "+34", flag: "🇪🇸" },
  { value: "Sri Lanka", label: "Sri Lanka", dialCode: "+94", flag: "🇱🇰" },
  { value: "Sudan", label: "Sudan", dialCode: "+249", flag: "🇸🇩" },
  { value: "Suriname", label: "Suriname", dialCode: "+597", flag: "🇸🇷" },
  { value: "Sweden", label: "Sweden", dialCode: "+46", flag: "🇸🇪" },
  { value: "Switzerland", label: "Switzerland", dialCode: "+41", flag: "🇨🇭" },
  { value: "Syria", label: "Syria", dialCode: "+963", flag: "🇸🇾" },
  { value: "Taiwan", label: "Taiwan", dialCode: "+886", flag: "🇹🇼" },
  { value: "Tajikistan", label: "Tajikistan", dialCode: "+992", flag: "🇹🇯" },
  { value: "Tanzania", label: "Tanzania", dialCode: "+255", flag: "🇹🇿" },
  { value: "Thailand", label: "Thailand", dialCode: "+66", flag: "🇹🇭" },
  { value: "Timor-Leste", label: "Timor-Leste", dialCode: "+670", flag: "🇹🇱" },
  { value: "Togo", label: "Togo", dialCode: "+228", flag: "🇹🇬" },
  { value: "Tonga", label: "Tonga", dialCode: "+676", flag: "🇹🇴" },
  { value: "Trinidad and Tobago", label: "Trinidad and Tobago", dialCode: "+1868", flag: "🇹🇹" },
  { value: "Tunisia", label: "Tunisia", dialCode: "+216", flag: "🇹🇳" },
  { value: "Turkey", label: "Turkey", dialCode: "+90", flag: "🇹🇷" },
  { value: "Turkmenistan", label: "Turkmenistan", dialCode: "+993", flag: "🇹🇲" },
  { value: "Tuvalu", label: "Tuvalu", dialCode: "+688", flag: "🇹🇻" },
  { value: "Uganda", label: "Uganda", dialCode: "+256", flag: "🇺🇬" },
  { value: "Ukraine", label: "Ukraine", dialCode: "+380", flag: "🇺🇦" },
  { value: "United Arab Emirates", label: "United Arab Emirates", dialCode: "+971", flag: "🇦🇪" },
  { value: "United States", label: "United States", dialCode: "+1", flag: "🇺🇸" },
  { value: "Uruguay", label: "Uruguay", dialCode: "+598", flag: "🇺🇾" },
  { value: "Uzbekistan", label: "Uzbekistan", dialCode: "+998", flag: "🇺🇿" },
  { value: "Vanuatu", label: "Vanuatu", dialCode: "+678", flag: "🇻🇺" },
];